### PR TITLE
Introduce sciml_train

### PR DESCRIPTION
**Pull request by ChrisRackauckas**
This is a starter PR for students interested in solving https://github.com/JuliaDiffEq/DiffEqFlux.jl/issues/120

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Needs to get tested and all of that. All of our tests should change over to this function and style. The README should all make use of it as well.

**Comment by ChrisRackauckas** [comment]
@pkofod is setting up the output with Optim's type a good idea?

**Comment by ChrisRackauckas** [comment]
From the tests:

TrackerAdjoint with ADAM:

```julia
 * Status: failure (reached maximum number of iterations)

 * Candidate solution
    Minimizer: [1.90e+00, 1.89e+00, 8.78e-01,  ...]
    Minimum:   6.817536e-03

 * Found with
    Algorithm:     ADAM
    Initial Point: [2.20e+00, 1.00e+00, 2.00e+00,  ...]

 * Convergence measures
    |x - x'|               = NaN ≰ 0.0e+00
    |x - x'|/|x'|          = NaN ≰ 0.0e+00
    |f(x) - f(x')|         = NaN ≰ 0.0e+00
    |f(x) - f(x')|/|f(x')| = NaN ≰ 0.0e+00
    |g(x)|                 = NaN ≰ 0.0e+00

 * Work counters
    Seconds run:   3  (vs limit Inf)
    Iterations:    100
    f(x) calls:    100
    ∇f(x) calls:   100
```

TrackerAdjoint with BFGS Optim

```julia
 * Status: failure (objective increased between iterations) (line search failed)

 * Candidate solution
    Minimizer: [1.96e+00, 1.96e+00, 1.70e+00,  ...]
    Minimum:   2.729345e-08

 * Found with
    Algorithm:     BFGS
    Initial Point: [2.20e+00, 1.00e+00, 2.00e+00,  ...]

 * Convergence measures
    |x - x'|               = 2.28e-06 ≰ 0.0e+00
    |x - x'|/|x'|          = 1.16e-06 ≰ 0.0e+00
    |f(x) - f(x')|         = 2.73e-14 ≰ 0.0e+00
    |f(x) - f(x')|/|f(x')| = 1.00e-06 ≰ 0.0e+00
    |g(x)|                 = 1.81e-03 ≰ 1.0e-08

 * Work counters
    Seconds run:   2  (vs limit Inf)
    Iterations:    11
    f(x) calls:    79
    ∇f(x) calls:   79
```

ForwardDiffSensitivity with ADAM

```julia
 * Status: failure (reached maximum number of iterations)

 * Candidate solution
    Minimizer: [1.75e+00, 1.72e+00, 1.18e+00,  ...]
    Minimum:   3.778992e-03

 * Found with
    Algorithm:     ADAM
    Initial Point: [2.20e+00, 1.00e+00, 2.00e+00,  ...]

 * Convergence measures
    |x - x'|               = NaN ≰ 0.0e+00
    |x - x'|/|x'|          = NaN ≰ 0.0e+00
    |f(x) - f(x')|         = NaN ≰ 0.0e+00
    |f(x) - f(x')|/|f(x')| = NaN ≰ 0.0e+00
    |g(x)|                 = NaN ≰ 0.0e+00

 * Work counters
    Seconds run:   1  (vs limit Inf)
    Iterations:    100
    f(x) calls:    100
    ∇f(x) calls:   100
```

with BFGS

```julia
 * Status: success

 * Candidate solution
    Minimizer: [1.85e+00, 1.85e+00, 1.22e+00,  ...]
    Minimum:   5.315246e-22

 * Found with
    Algorithm:     BFGS
    Initial Point: [2.20e+00, 1.00e+00, 2.00e+00,  ...]

 * Convergence measures
    |x - x'|               = 1.67e-09 ≰ 0.0e+00
    |x - x'|/|x'|          = 9.02e-10 ≰ 0.0e+00
    |f(x) - f(x')|         = 5.78e-17 ≰ 0.0e+00
    |f(x) - f(x')|/|f(x')| = 1.09e+05 ≰ 0.0e+00
    |g(x)|                 = 5.25e-11 ≤ 1.0e-08

 * Work counters
    Seconds run:   0  (vs limit Inf)
    Iterations:    10
    f(x) calls:    35
    ∇f(x) calls:   35
```

Adjoints with ADAM

```julia
 * Status: failure (reached maximum number of iterations)

 * Candidate solution
    Minimizer: [1.90e+00, 1.89e+00, 8.78e-01,  ...]
    Minimum:   6.817536e-03

 * Found with
    Algorithm:     ADAM
    Initial Point: [2.20e+00, 1.00e+00, 2.00e+00,  ...]

 * Convergence measures
    |x - x'|               = NaN ≰ 0.0e+00
    |x - x'|/|x'|          = NaN ≰ 0.0e+00
    |f(x) - f(x')|         = NaN ≰ 0.0e+00
    |f(x) - f(x')|/|f(x')| = NaN ≰ 0.0e+00
    |g(x)|                 = NaN ≰ 0.0e+00

 * Work counters
    Seconds run:   3  (vs limit Inf)
    Iterations:    100
    f(x) calls:    100
    ∇f(x) calls:   100
```

```julia
 * Status: failure (objective increased between iterations) (line search failed)

 * Candidate solution
    Minimizer: [1.96e+00, 1.96e+00, 1.70e+00,  ...]
    Minimum:   2.729345e-08

 * Found with
    Algorithm:     BFGS
    Initial Point: [2.20e+00, 1.00e+00, 2.00e+00,  ...]

 * Convergence measures
    |x - x'|               = 2.28e-06 ≰ 0.0e+00
    |x - x'|/|x'|          = 1.16e-06 ≰ 0.0e+00
    |f(x) - f(x')|         = 2.73e-14 ≰ 0.0e+00
    |f(x) - f(x')|/|f(x')| = 1.00e-06 ≰ 0.0e+00
    |g(x)|                 = 1.81e-03 ≰ 1.0e-08

 * Work counters
    Seconds run:   2  (vs limit Inf)
    Iterations:    11
    f(x) calls:    79
    ∇f(x) calls:   79
```

Conclusion: BFGS is consistently about 5 orders of magnitude better with less effort.

**Comment by pkofod** [comment]
> Also, is there a reason why the initial stepnorm is so sensitive?

Wrt this... The question is that before the second iteration we have no second order information (unless given), so the hessian approximation is just `I`. This means that it will attempt to take the step `-gradient` and that can take you into funky regions. This is why we're also restricting the initial step in Pumas.

**Comment by ChrisRackauckas** [comment]
From what I can tell it almost always needs to be restricted. Would it be good to change the default to 0.01?

**Comment by pkofod** [comment]
You could. There have been various suggestions, but most descriptions assume that the initial step is the full gradient. Alternatively you can specify a preconditioner, you can supply curvature information through the initial inverse hessian approximation or yeah, an initial step norm. I never really benchmarked it. I only added the possibility because we looked at it in the Pumas context :)

**Pull request merged**
